services:
  registry:
    image: registry:${REGISTRY_TAG:-latest}
    container_name: docker-registry
    restart: unless-stopped

    ports:
      - "5000:5000"

    volumes:
      - registry_data:/var/lib/registry

  registry-ui:
    image: joxit/docker-registry-ui:${JOXIT_TAG:-latest}
    container_name: docker-registry-ui
    restart: unless-stopped

    environment:
      - REGISTRY_TITLE=Collective Registry
      - NGINX_PROXY_PASS_URL=http://registry:5000
      - SINGLE_REGISTRY=true
      - DELETE_IMAGES=true
      - SHOW_CONTENT_DIGEST=true

    depends_on:
      - registry

    ports:
      - "8080:80"

volumes:
  registry_data:
