services:
  gshock-time-server:
    image: collective.local:5000/gshock-time-server:${GSHOCK_TAG:-915a568}
    container_name: gshock-time-server
    platform: ${PLATFORM:-linux/arm64}
    restart: unless-stopped

    volumes:
      # Allow Bleak to communicate with the host's BlueZ daemon
      - /run/dbus:/run/dbus:ro

    environment:
      - BLEAK_DBUS_AUTH_UID=0
  n8n:
    image: n8nio/n8n
    container_name: n8n:${N8N_TAG:-latest}
    platform: ${PLATFORM:-linux/arm64}
    restart: unless-stopped

    ports:
      - "5678:5678"

    environment:
      GENERIC_TIMEZONE: ${TIMEZONE:-Europe/London}
      TZ: ${TIMEZONE:-Europe/London}
      N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: "true"

    volumes:
      - n8n_data:/home/node/.n8n

volumes:
  n8n_data:
