services:
  uptime-kuma:
    image: louislam/uptime-kuma:${UPTIME_KUMA_TAG:-2-slim-rootless}
    platform: ${PLATFORM:-linux/arm64}
    restart: unless-stopped

    ports:
      - "3001:3001"

    volumes:
      - uptime_kuma_data:/app/data

volumes:
  uptime_kuma_data:
